Add Html and css files
Lucash2022/Portfolio pull request #1
Opened 2022-10-27 04:41 UTC by Lucash2022

2022-10-27 16:08 UTC, Kamba56 reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no pull request description. Please add a pull request description that summarizes all the changes you implemented on the branch. Kindly check [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects) for more information.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-27 16:44 UTC, Lucash2022 commented
> Hi <STUDENT_MENTION>,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has no pull request description. Please add a pull request description that summarizes all the changes you implemented on the branch. Kindly check [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects) for more information.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-27 17:25 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @Lucash2022, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-   No linter errors. :heavy_check_mark: 
-   Good README file. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966) 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [x] At this moment, below is how your page appear. Kindly look into it and fix the issue.

### Your Design

![your-page](https://user-images.githubusercontent.com/26597432/198357524-07e04d53-95eb-458d-967f-bf181a7317ff.png)

2022-10-27 17:25 UTC, Qoosim commented on index.html
> +  </div>
- [ ] Kindly remove this part of the project. It is not part of it

2022-10-27 17:25 UTC, Qoosim commented on index.html
> +</div>
- [ ] This section is supposed to be your header where you are going to have your logo and hamburger. Your logo should be a link to your home page (`<a>`) tag. That's in line with the standard way of a professional website. And your hamburger should be wrapped inside a `<nav>` tag with the hamburger icon inside. Kindly look into these and fix them.

2022-10-27 17:25 UTC, Qoosim commented on index.html
> +    you see and have a project you need coded, don’t hestiate to contact me.</div>
- [ ] It is required to use `<p>` tag instead of `<div>`  tag for semantic reason. Kindly change it.

2022-10-28 07:15 UTC, Lucash2022 commented on index.html
> +  </div>
I used it to create the following. Do you have a suggestion on how I would do it with out the above code?
![phone bars](https://user-images.githubusercontent.com/41428579/198526599-8291968f-3e3b-4073-bca6-5b7e2dac6844.jpg)

2022-10-28 12:37 UTC, Kamba56 commented on index.html
> +  </div>
Hi @Lucash2022, You don't need that part. That is just in the figma design to make the design look realistic

2022-10-28 16:30 UTC, Lucash2022 commented on index.html
> +    you see and have a project you need coded, don’t hestiate to contact me.</div>
Made this change

2022-10-28 16:30 UTC, Lucash2022 commented on index.html
> +</div>
Applied this change

2022-10-28 16:30 UTC, Lucash2022 commented on index.html
> +  </div>
Removed that entire part

2022-10-28 16:51 UTC, algerina approved these changes
Hi @Lucash2022 , 
Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
<img src="https://media2.giphy.com/media/2MQi4hG5NBBFCXdKnR/giphy.gif"/>

 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-28 16:51 UTC, algerina commented on index.html
> +          you see and have a project you need coded, don’t hestiate to contact me.
- [ Optional]  You did a great job however, this is supposed to be your personal portfolio. It will be better to replace the `logo` by your own name or Logo and the text `I'm Marine...` by your own name and informations.

2022-10-30 08:08 UTC, merged